import './global.css';
import Header from '../../common/components/header/header';

export const metadata = {
  title: 'Welcome to registration',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
